require 'project_euler/problem_2'
require 'project_euler/problem_3'
require 'project_euler/problem_4'
require 'project_euler/problem_6'
require 'project_euler/problem_7'
require 'project_euler/problem_8'
